# Generated by Django 5.0.6 on 2024-06-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='participant',
            field=models.ManyToManyField(to='participantes.participant'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ManyToManyField(to='eventos.event'),
        ),
    ]
